### ISSUE TITLE
TranslatorHub bug

### ISSUE THREAD

**Issue by beliboba** [Arustinal/fluentogram#20]
Project structure
app/
├─ lang/
│  ├─ ru.ftl
│  ├─ en-US.ftl
├─ src/
│  ├─ core/
│  │  ├─ startapp.py

startapp.py:

```
...
translator_hub = TranslatorHub(
        {
            "ru": ("ru", "en"),
            "en": ("en",)
        },
        [
            FluentTranslator("en", translator=FluentBundle.from_files("en-US", "lang/en-US.ftl")),
            FluentTranslator("ru", translator=FluentBundle.from_files("ru", "lang/ru.ftl"))
        ],
    )
...
```

Error when running:
```
Traceback (most recent call last):
  File "C:\Users\Beliboba\PycharmProjects\***\main.py", line 9, in <module>
    asyncio.run(
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Beliboba\PycharmProjects\***\src\core\startapp.py", line 58, in run
    await _start_app(
  File "C:\Users\Beliboba\PycharmProjects\***\src\core\startapp.py", line 40, in _start_app
    await asyncio.gather(
  File "C:\Users\Beliboba\PycharmProjects\***\src\core\startapp.py", line 27, in _start_bot
    FluentTranslator("en", translator=FluentBundle.from_files("en-US", "lang/en-US.ftl")),
  File "C:\Users\Beliboba\PycharmProjects\***\venv\lib\site-packages\fluent_compiler\bundle.py", line 45, in from_files
    [FtlResource.from_file(f) for f in filenames],
  File "C:\Users\Beliboba\PycharmProjects\***\venv\lib\site-packages\fluent_compiler\bundle.py", line 45, in <listcomp>
    [FtlResource.from_file(f) for f in filenames],
  File "C:\Users\Beliboba\PycharmProjects\***\venv\lib\site-packages\fluent_compiler\resource.py", line 18, in from_file
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'l'
```

**Comment by beliboba** [comment]
solved by changing translatorhub to this
```
translator_hub = TranslatorHub(
        {
            "ru": ("ru", "en"),
            "en": ("en",)
        },
        [
            FluentTranslator("en", translator=FluentBundle.from_files("en-US", ["lang/en-US.ftl"])),
            FluentTranslator("ru", translator=FluentBundle.from_files("ru", ["lang/ru.ftl"]))
        ],
    )
```
